
import { TarotCard, LenormandCard } from './types';

export const TAROT_DECK: TarotCard[] = [
    { name: 'El Loco', arcana: 'Major', imageName: 'the-fool' },
    { name: 'El Mago', arcana: 'Major', imageName: 'the-magician' },
    { name: 'La Sacerdotisa', arcana: 'Major', imageName: 'the-high-priestess' },
    { name: 'La Emperatriz', arcana: 'Major', imageName: 'the-empress' },
    { name: 'El Emperador', arcana: 'Major', imageName: 'the-emperor' },
    { name: 'El Hierofante', arcana: 'Major', imageName: 'the-hierophant' },
    { name: 'Los Enamorados', arcana: 'Major', imageName: 'the-lovers' },
    { name: 'El Carro', arcana: 'Major', imageName: 'the-chariot' },
    { name: 'La Fuerza', arcana: 'Major', imageName: 'strength' },
    { name: 'El Ermitaño', arcana: 'Major', imageName: 'the-hermit' },
    { name: 'La Rueda de la Fortuna', arcana: 'Major', imageName: 'wheel-of-fortune' },
    { name: 'La Justicia', arcana: 'Major', imageName: 'justice' },
    { name: 'El Colgado', arcana: 'Major', imageName: 'the-hanged-man' },
    { name: 'La Muerte', arcana: 'Major', imageName: 'death' },
    { name: 'La Templanza', arcana: 'Major', imageName: 'temperance' },
    { name: 'El Diablo', arcana: 'Major', imageName: 'the-devil' },
    { name: 'La Torre', arcana: 'Major', imageName: 'the-tower' },
    { name: 'La Estrella', arcana: 'Major', imageName: 'the-star' },
    { name: 'La Luna', arcana: 'Major', imageName: 'the-moon' },
    { name: 'El Sol', arcana: 'Major', imageName: 'the-sun' },
    { name: 'El Juicio', arcana: 'Major', imageName: 'judgement' },
    { name: 'El Mundo', arcana: 'Major', imageName: 'the-world' },
    { name: 'As de Bastos', arcana: 'Minor', imageName: 'ace-of-wands' },
    { name: 'Dos de Bastos', arcana: 'Minor', imageName: 'two-of-wands' },
    { name: 'Tres de Bastos', arcana: 'Minor', imageName: 'three-of-wands' },
    { name: 'Cuatro de Bastos', arcana: 'Minor', imageName: 'four-of-wands' },
    { name: 'Cinco de Bastos', arcana: 'Minor', imageName: 'five-of-wands' },
    { name: 'Seis de Bastos', arcana: 'Minor', imageName: 'six-of-wands' },
    { name: 'Siete de Bastos', arcana: 'Minor', imageName: 'seven-of-wands' },
    { name: 'Ocho de Bastos', arcana: 'Minor', imageName: 'eight-of-wands' },
    { name: 'Nueve de Bastos', arcana: 'Minor', imageName: 'nine-of-wands' },
    { name: 'Diez de Bastos', arcana: 'Minor', imageName: 'ten-of-wands' },
    { name: 'Sota de Bastos', arcana: 'Minor', imageName: 'page-of-wands' },
    { name: 'Caballero de Bastos', arcana: 'Minor', imageName: 'knight-of-wands' },
    { name: 'Reina de Bastos', arcana: 'Minor', imageName: 'queen-of-wands' },
    { name: 'Rey de Bastos', arcana: 'Minor', imageName: 'king-of-wands' },
    { name: 'As de Copas', arcana: 'Minor', imageName: 'ace-of-cups' },
    { name: 'Dos de Copas', arcana: 'Minor', imageName: 'two-of-cups' },
    { name: 'Tres de Copas', arcana: 'Minor', imageName: 'three-of-cups' },
    { name: 'Cuatro de Copas', arcana: 'Minor', imageName: 'four-of-cups' },
    { name: 'Cinco de Copas', arcana: 'Minor', imageName: 'five-of-cups' },
    { name: 'Seis de Copas', arcana: 'Minor', imageName: 'six-of-cups' },
    { name: 'Siete de Copas', arcana: 'Minor', imageName: 'seven-of-cups' },
    { name: 'Ocho de Copas', arcana: 'Minor', imageName: 'eight-of-cups' },
    { name: 'Nueve de Copas', arcana: 'Minor', imageName: 'nine-of-cups' },
    { name: 'Diez de Copas', arcana: 'Minor', imageName: 'ten-of-cups' },
    { name: 'Sota de Copas', arcana: 'Minor', imageName: 'page-of-cups' },
    { name: 'Caballero de Copas', arcana: 'Minor', imageName: 'knight-of-cups' },
    { name: 'Reina de Copas', arcana: 'Minor', imageName: 'queen-of-cups' },
    { name: 'Rey de Copas', arcana: 'Minor', imageName: 'king-of-cups' },
    { name: 'As de Espadas', arcana: 'Minor', imageName: 'ace-of-swords' },
    { name: 'Dos de Espadas', arcana: 'Minor', imageName: 'two-of-swords' },
    { name: 'Tres de Espadas', arcana: 'Minor', imageName: 'three-of-swords' },
    { name: 'Cuatro de Espadas', arcana: 'Minor', imageName: 'four-of-swords' },
    { name: 'Cinco de Espadas', arcana: 'Minor', imageName: 'five-of-swords' },
    { name: 'Seis de Espadas', arcana: 'Minor', imageName: 'six-of-swords' },
    { name: 'Siete de Espadas', arcana: 'Minor', imageName: 'seven-of-swords' },
    { name: 'Ocho de Espadas', arcana: 'Minor', imageName: 'eight-of-swords' },
    { name: 'Nueve de Espadas', arcana: 'Minor', imageName: 'nine-of-swords' },
    { name: 'Diez de Espadas', arcana: 'Minor', imageName: 'ten-of-swords' },
    { name: 'Sota de Espadas', arcana: 'Minor', imageName: 'page-of-swords' },
    { name: 'Caballero de Espadas', arcana: 'Minor', imageName: 'knight-of-swords' },
    { name: 'Reina de Espadas', arcana: 'Minor', imageName: 'queen-of-swords' },
    { name: 'Rey de Espadas', arcana: 'Minor', imageName: 'king-of-swords' },
    { name: 'As de Oros', arcana: 'Minor', imageName: 'ace-of-pentacles' },
    { name: 'Dos de Oros', arcana: 'Minor', imageName: 'two-of-pentacles' },
    { name: 'Tres de Oros', arcana: 'Minor', imageName: 'three-of-pentacles' },
    { name: 'Cuatro de Oros', arcana: 'Minor', imageName: 'four-of-pentacles' },
    { name: 'Cinco de Oros', arcana: 'Minor', imageName: 'five-of-pentacles' },
    { name: 'Seis de Oros', arcana: 'Minor', imageName: 'six-of-pentacles' },
    { name: 'Siete de Oros', arcana: 'Minor', imageName: 'seven-of-pentacles' },
    { name: 'Ocho de Oros', arcana: 'Minor', imageName: 'eight-of-pentacles' },
    { name: 'Nueve de Oros', arcana: 'Minor', imageName: 'nine-of-pentacles' },
    { name: 'Diez de Oros', arcana: 'Minor', imageName: 'ten-of-pentacles' },
    { name: 'Sota de Oros', arcana: 'Minor', imageName: 'page-of-pentacles' },
    { name: 'Caballero de Oros', arcana: 'Minor', imageName: 'knight-of-pentacles' },
    { name: 'Reina de Oros', arcana: 'Minor', imageName: 'queen-of-pentacles' },
    { name: 'Rey de Oros', arcana: 'Minor', imageName: 'king-of-pentacles' }
];

export const LENORMAND_DECK: LenormandCard[] = [
    { number: 1, name: 'El Jinete', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/01_Rider_zcbuzc.png' },
    { number: 2, name: 'El Trébol', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/02_Clover_wetw13.png' },
    { number: 3, name: 'El Barco', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/03_Ship_v2y96f.png' },
    { number: 4, name: 'La Casa', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/04_House_tid8ot.png' },
    { number: 5, name: 'El Árbol', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/05_Tree_ljijc7.png' },
    { number: 6, name: 'Las Nubes', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/06_Clouds_gj8nih.png' },
    { number: 7, name: 'La Serpiente', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/07_Snake_qq1xd1.png' },
    { number: 8, name: 'El Ataúd', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/08_Coffin_yyhmnd.png' },
    { number: 9, name: 'El Ramo', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/09_Bouquet_swg9mc.png' },
    { number: 10, name: 'La Guadaña', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/10_Scythe_fcfrcn.png' },
    { number: 11, name: 'Las Varas', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/11_Whip_fmslhc.png' },
    { number: 12, name: 'Los Pájaros', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/12_Birds_vlqidf.png' },
    { number: 13, name: 'La Niña', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/13_Child_jo6rg9.png' },
    { number: 14, name: 'El Zorro', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/14_Fox_uyjxw2.png' },
    { number: 15, name: 'El Oso', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/15_Bear_xof5ze.png' },
    { number: 16, name: 'La Estrella', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/16_Star_yuj6mi.png' },
    { number: 17, name: 'La Cigüeña', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/17_Stork_m5rcpv.png' },
    { number: 18, name: 'El Perro', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/18_Dog_tqwkgp.png' },
    { number: 19, name: 'La Torre', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/19_Tower_gv9ubv.png' },
    { number: 20, name: 'El Jardín', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/20_Garden_ntpswj.png' },
    { number: 21, name: 'La Montaña', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/21_Mountain_qszuy8.png' },
    { number: 22, name: 'Los Caminos', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/22_Crossroads_p0cdkb.png' },
    { number: 23, name: 'Los Ratones', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/23_Mice_gnkgps.png' },
    { number: 24, name: 'El Corazón', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/24_Heart_grxkio.png' },
    { number: 25, name: 'El Anillo', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/25_Ring_rgrc8o.png' },
    { number: 26, name: 'El Libro', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/26_Book_rynxvp.png' },
    { number: 27, name: 'La Carta', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/27_Letter_d9r0u3.png' },
    { number: 28, name: 'El Hombre', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/28_Man_s0iges.png' },
    { number: 29, name: 'La Mujer', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/29_Woman_bjntop.png' },
    { number: 30, name: 'Los Lirios', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/30_Lily_pdam9j.png' },
    { number: 31, name: 'El Sol', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/31_Sun_tosqbm.png' },
    { number: 32, name: 'La Luna', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/32_Moon_i0wonl.png' },
    { number: 33, name: 'La Llave', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/33_Key_blvspw.png' },
    { number: 34, name: 'Los Peces', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/34_Fish_bp1rdj.png' },
    { number: 35, name: 'El Ancla', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/35_Anchor_qkw51w.png' },
    { number: 36, name: 'La Cruz', imageUrl: 'https://res.cloudinary.com/dp9yhv2p6/image/upload/36_Cross_ihspse.png' },
];
