
import { TarotCard, LenormandCard } from './types';

export const TAROT_DECK: TarotCard[] = [
    { name: 'El Loco', arcana: 'Major', imageName: 'the-fool' },
    { name: 'El Mago', arcana: 'Major', imageName: 'the-magician' },
    { name: 'La Sacerdotisa', arcana: 'Major', imageName: 'the-high-priestess' },
    { name: 'La Emperatriz', arcana: 'Major', imageName: 'the-empress' },
    { name: 'El Emperador', arcana: 'Major', imageName: 'the-emperor' },
    { name: 'El Hierofante', arcana: 'Major', imageName: 'the-hierophant' },
    { name: 'Los Enamorados', arcana: 'Major', imageName: 'the-lovers' },
    { name: 'El Carro', arcana: 'Major', imageName: 'the-chariot' },
    { name: 'La Fuerza', arcana: 'Major', imageName: 'strength' },
    { name: 'El Ermitaño', arcana: 'Major', imageName: 'the-hermit' },
    { name: 'La Rueda de la Fortuna', arcana: 'Major', imageName: 'wheel-of-fortune' },
    { name: 'La Justicia', arcana: 'Major', imageName: 'justice' },
    { name: 'El Colgado', arcana: 'Major', imageName: 'the-hanged-man' },
    { name: 'La Muerte', arcana: 'Major', imageName: 'death' },
    { name: 'La Templanza', arcana: 'Major', imageName: 'temperance' },
    { name: 'El Diablo', arcana: 'Major', imageName: 'the-devil' },
    { name: 'La Torre', arcana: 'Major', imageName: 'the-tower' },
    { name: 'La Estrella', arcana: 'Major', imageName: 'the-star' },
    { name: 'La Luna', arcana: 'Major', imageName: 'the-moon' },
    { name: 'El Sol', arcana: 'Major', imageName: 'the-sun' },
    { name: 'El Juicio', arcana: 'Major', imageName: 'judgement' },
    { name: 'El Mundo', arcana: 'Major', imageName: 'the-world' },
    { name: 'As de Bastos', arcana: 'Minor', imageName: 'ace-of-wands' },
    { name: 'Dos de Bastos', arcana: 'Minor', imageName: 'two-of-wands' },
    { name: 'Tres de Bastos', arcana: 'Minor', imageName: 'three-of-wands' },
    { name: 'Cuatro de Bastos', arcana: 'Minor', imageName: 'four-of-wands' },
    { name: 'Cinco de Bastos', arcana: 'Minor', imageName: 'five-of-wands' },
    { name: 'Seis de Bastos', arcana: 'Minor', imageName: 'six-of-wands' },
    { name: 'Siete de Bastos', arcana: 'Minor', imageName: 'seven-of-wands' },
    { name: 'Ocho de Bastos', arcana: 'Minor', imageName: 'eight-of-wands' },
    { name: 'Nueve de Bastos', arcana: 'Minor', imageName: 'nine-of-wands' },
    { name: 'Diez de Bastos', arcana: 'Minor', imageName: 'ten-of-wands' },
    { name: 'Sota de Bastos', arcana: 'Minor', imageName: 'page-of-wands' },
    { name: 'Caballero de Bastos', arcana: 'Minor', imageName: 'knight-of-wands' },
    { name: 'Reina de Bastos', arcana: 'Minor', imageName: 'queen-of-wands' },
    { name: 'Rey de Bastos', arcana: 'Minor', imageName: 'king-of-wands' },
    { name: 'As de Copas', arcana: 'Minor', imageName: 'ace-of-cups' },
    { name: 'Dos de Copas', arcana: 'Minor', imageName: 'two-of-cups' },
    { name: 'Tres de Copas', arcana: 'Minor', imageName: 'three-of-cups' },
    { name: 'Cuatro de Copas', arcana: 'Minor', imageName: 'four-of-cups' },
    { name: 'Cinco de Copas', arcana: 'Minor', imageName: 'five-of-cups' },
    { name: 'Seis de Copas', arcana: 'Minor', imageName: 'six-of-cups' },
    { name: 'Siete de Copas', arcana: 'Minor', imageName: 'seven-of-cups' },
    { name: 'Ocho de Copas', arcana: 'Minor', imageName: 'eight-of-cups' },
    { name: 'Nueve de Copas', arcana: 'Minor', imageName: 'nine-of-cups' },
    { name: 'Diez de Copas', arcana: 'Minor', imageName: 'ten-of-cups' },
    { name: 'Sota de Copas', arcana: 'Minor', imageName: 'page-of-cups' },
    { name: 'Caballero de Copas', arcana: 'Minor', imageName: 'knight-of-cups' },
    { name: 'Reina de Copas', arcana: 'Minor', imageName: 'queen-of-cups' },
    { name: 'Rey de Copas', arcana: 'Minor', imageName: 'king-of-cups' },
    { name: 'As de Espadas', arcana: 'Minor', imageName: 'ace-of-swords' },
    { name: 'Dos de Espadas', arcana: 'Minor', imageName: 'two-of-swords' },
    { name: 'Tres de Espadas', arcana: 'Minor', imageName: 'three-of-swords' },
    { name: 'Cuatro de Espadas', arcana: 'Minor', imageName: 'four-of-swords' },
    { name: 'Cinco de Espadas', arcana: 'Minor', imageName: 'five-of-swords' },
    { name: 'Seis de Espadas', arcana: 'Minor', imageName: 'six-of-swords' },
    { name: 'Siete de Espadas', arcana: 'Minor', imageName: 'seven-of-swords' },
    { name: 'Ocho de Espadas', arcana: 'Minor', imageName: 'eight-of-swords' },
    { name: 'Nueve de Espadas', arcana: 'Minor', imageName: 'nine-of-swords' },
    { name: 'Diez de Espadas', arcana: 'Minor', imageName: 'ten-of-swords' },
    { name: 'Sota de Espadas', arcana: 'Minor', imageName: 'page-of-swords' },
    { name: 'Caballero de Espadas', arcana: 'Minor', imageName: 'knight-of-swords' },
    { name: 'Reina de Espadas', arcana: 'Minor', imageName: 'queen-of-swords' },
    { name: 'Rey de Espadas', arcana: 'Minor', imageName: 'king-of-swords' },
    { name: 'As de Oros', arcana: 'Minor', imageName: 'ace-of-pentacles' },
    { name: 'Dos de Oros', arcana: 'Minor', imageName: 'two-of-pentacles' },
    { name: 'Tres de Oros', arcana: 'Minor', imageName: 'three-of-pentacles' },
    { name: 'Cuatro de Oros', arcana: 'Minor', imageName: 'four-of-pentacles' },
    { name: 'Cinco de Oros', arcana: 'Minor', imageName: 'five-of-pentacles' },
    { name: 'Seis de Oros', arcana: 'Minor', imageName: 'six-of-pentacles' },
    { name: 'Siete de Oros', arcana: 'Minor', imageName: 'seven-of-pentacles' },
    { name: 'Ocho de Oros', arcana: 'Minor', imageName: 'eight-of-pentacles' },
    { name: 'Nueve de Oros', arcana: 'Minor', imageName: 'nine-of-pentacles' },
    { name: 'Diez de Oros', arcana: 'Minor', imageName: 'ten-of-pentacles' },
    { name: 'Sota de Oros', arcana: 'Minor', imageName: 'page-of-pentacles' },
    { name: 'Caballero de Oros', arcana: 'Minor', imageName: 'knight-of-pentacles' },
    { name: 'Reina de Oros', arcana: 'Minor', imageName: 'queen-of-pentacles' },
    { name: 'Rey de Oros', arcana: 'Minor', imageName: 'king-of-pentacles' },
];


export const LENORMAND_DECK: LenormandCard[] = [
    { name: 'El Jinete', number: 1 },
    { name: 'El Trébol', number: 2 },
    { name: 'El Barco', number: 3 },
    { name: 'La Casa', number: 4 },
    { name: 'El Árbol', number: 5 },
    { name: 'Las Nubes', number: 6 },
    { name: 'La Serpiente', number: 7 },
    { name: 'El Ataúd', number: 8 },
    { name: 'El Ramo', number: 9 },
    { name: 'La Guadaña', number: 10 },
    { name: 'Las Varas', number: 11 },
    { name: 'Los Pájaros', number: 12 },
    { name: 'La Niña', number: 13 },
    { name: 'El Zorro', number: 14 },
    { name: 'El Oso', number: 15 },
    { name: 'La Estrella', number: 16 },
    { name: 'La Cigüeña', number: 17 },
    { name: 'El Perro', number: 18 },
    { name: 'La Torre', number: 19 },
    { name: 'El Jardín', number: 20 },
    { name: 'La Montaña', number: 21 },
    { name: 'El Camino', number: 22 },
    { name: 'Los Ratones', number: 23 },
    { name: 'El Corazón', number: 24 },
    { name: 'El Anillo', number: 25 },
    { name: 'El Libro', number: 26 },
    { name: 'La Carta', number: 27 },
    { name: 'El Hombre', number: 28 },
    { name: 'La Mujer', number: 29 },
    { name: 'Los Lirios', number: 30 },
    { name: 'El Sol', number: 31 },
    { name: 'La Luna', number: 32 },
    { name: 'La Llave', number: 33 },
    { name: 'Los Peces', number: 34 },
    { name: 'El Ancla', number: 35 },
    { name: 'La Cruz', number: 36 },
];